version: '4'
services:
  mysql:
    image: mysql:8.0.32
    container_name: inventory-service-mysql
    ports:
      - "3316:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=12345678
    volumes:
      - ./mysql_data:/var/lib/mysql
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql